### ISSUE TITLE
按照你的方法自建项目中.so文件没有复制到.apk中

### ISSUE THREAD

**Issue by elegracer** [Martin20150405/OpenCV4AndroidWithCmake#1]
你好，在你的设置opencv cmake的那篇文章中，我按照你的方法，但是最后.apk文件里没有包含那两个.so文件，并且将你的项目下载下来，发现jniLibs这个文件夹优点特殊，貌似被认为是某种resource folder或assets folder，请问你是怎么让.so文件自动复制到.apk文件里的啊？谢谢

**Comment by Martin20150405** [comment]
@soaph 
http://blog.csdn.net/Martin20150405/article/details/53284442 已更新可能的解决方案

**Comment by elegracer** [comment]
非常感谢！
