### ISSUE TITLE
Device support x86

### ISSUE THREAD

**Issue by serrokitskiy** [Martin20150405/OpenCV4AndroidWithCmake#2]
I need run this app on **x86 emulator**.

![2017-07-24 12 00 29](https://user-images.githubusercontent.com/13848224/28515856-d6fa8f24-7067-11e7-8bc0-04e32b476d13.png)

I can find in .../OpenCV-android-sdk/sdk/native/libs/x86/libopencv_java3.so
Where I can find **libopencv_java.so for x86**?

I changed
![2017-07-24 12 07 25](https://user-images.githubusercontent.com/13848224/28516111-b93abc74-7068-11e7-9e69-bc4d36f62a67.png)

![2017-07-24 12 05 11](https://user-images.githubusercontent.com/13848224/28516036-712caf6e-7068-11e7-8145-d8268b311bae.png)

![2017-07-24 12 05 56](https://user-images.githubusercontent.com/13848224/28516055-814afd6a-7068-11e7-9e83-c9acf8bebf4f.png)

**Comment by Martin20150405** [comment]
@serrokitskiy It's in the OpenCVManager.

**Comment by serrokitskiy** [comment]
@Martin20150405 Ok. Thank. I will try find where I can download libopencv_java.so for x86. Maybe you have link for download?)

**Comment by serrokitskiy** [comment]
@Martin20150405 I finded))) https://github.com/nehiljain/opencv4android/blob/master/sdk/native/libs/x86/libopencv_java.so
Thanks!
