### ISSUE TITLE
No slam2 compiled

### ISSUE THREAD

**Issue by erickingxu** [Martin20150405/OpenCV4AndroidWithCmake#4]
Hi @Martin20150405 ,
Thx for your work, I used orb-slam2 for android studio , but metting with some problem, can you show us with orb-slam2 in Android studio.

Thx

**Comment by Martin20150405** [comment]
This project is irrelevant with slam.
Please check [here](https://github.com/Martin20150405/NetDisk/tree/master/ORB-SLAM2-Android) for more details.
